language: python
python:
  - '3.6'
services:
  - mongodb
  - docker
install:
  # TODO DONT USE THE REAL INGINIOUS VERSION AS THEY DONT MERGE THIS PR :
  # https://github.com/UCL-INGI/INGInious/pull/415
  # - pip3 install git+https://github.com/UCL-INGI/INGInious
  - pip3 install git+https://github.com/jy95/INGInious
  - docker pull ingi/inginious-c-base
  - docker pull ingi/inginious-c-default
  - docker pull ingi/inginious-c-java8scala
  # To print beautiful table here
  - pip3 install beautifultable
  - pip3 install colored
before_script:
  - python3 travis_setup.py
script:
  - inginious-autotest . LEPL1402 -l
  # check consistance
  - ./check_requirements.py
notifications:
  slack:
      on_success: change
      on_failure: always